### ISSUE TITLE
SDK installers have disappeared

### ISSUE THREAD

**Issue by IanCirrus** [openhwgroup/core-v-sdk#15]
Hi,

I was just trying to install the Core SDK on a new machine, but the Windows installer is no longer on https://downloads.openhwgroup.org/

Please can it be reinstated?

Thanks,

Ian

**Comment by promodkumar-ashling** [comment]
That's surprising , I think @zarubaf or @suppamax would be the right people to check this.

**Comment by suppamax** [comment]
Should be back now

**Comment by IanCirrus** [comment]
Excellent. Thank you.
And I see v0.0.5 is there now as well :-)
